spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/medsys_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

## Jwt Secret que será utilizada em ambiente de DEV, em produção deve ser injetada via variável de ambiente ou serviço de gerenciamento de segredos
jwt:
  secret: "dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3ItbWVkc3lzLWp3dC0yNTZiaXRz"
  expiration-ms: 86400000